# Generated by Django 4.2.13 on 2024-06-17 02:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_product_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="minimum_sale_unit",
            field=models.DecimalField(
                decimal_places=3, max_digits=10, verbose_name="Minimum Sale Unit"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="stock_quantity",
            field=models.IntegerField(default=0, verbose_name="Stock Quantity"),
        ),
    ]
