# Generated by Django 4.2.13 on 2024-06-17 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_product_minimum_sale_unit_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="brand",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.brand",
                verbose_name="Brand",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="unit_of_measure",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.unitofmeasure",
                verbose_name="Unit of Measure",
            ),
        ),
    ]
