# Generated by Django 4.2.13 on 2024-06-17 02:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_product_brand_alter_product_unit_of_measure"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="minimum_unit_price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Minimum Unit Price"
            ),
        ),
    ]
