# Generated by Django 4.2.13 on 2024-06-24 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_productimage_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='url',
        ),
    ]
