# Generated by Django 4.2.13 on 2024-06-24 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_image_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='brands', to='core.company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='category',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='categories', to='core.company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='image',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='images', to='core.company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='partners', to='core.company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='core.brand', verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='products', to='core.company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_of_measure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='core.unitofmeasure', verbose_name='Unit of Measure'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_categories', to='core.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_categories', to='core.company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_categories', to='core.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_images', to='core.company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='core.image', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='core.productvariant', verbose_name='Product Variant'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_variants', to='core.company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='unitofmeasure',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='units_of_measure', to='core.company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='variantoption',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='variant_options', to='core.company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='variantvalue',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='variant_values', to='core.company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='variantvalue',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_values', to='core.variantoption', verbose_name='Variant Option'),
        ),
    ]
